# Copyright (C) 2023 Mateus de Lima Oliveira

all:
	make -C templatizer
	make -C templatizer-sys

clean:
	make -C templatizer-sys clean
	make -C templatizer clean

.PHONY: templatizer-sys templatizer clean
