# Copyright (C) 2022 Mateus de Lima Oliveira

all:
	make -C input
	make -C database

install:
	make -C input install
	make -C database install

clean:
	make -C input clean
	make -C database clean

.PHONY: all install clean
