runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    # GitHub does not provide an official runner for Alpine Linux
    - name: Setup latest Alpine Linux
      uses: jirutka/setup-alpine@v1
    - name: Run script inside Alpine chroot as root
      run: |
        cat /etc/alpine-release
        apk update
        apk add sudo
        sudo make dependencies
        make
        make test
      shell: alpine.sh {0}

